version: '3.8'

services:
  postgres-local:
    image: postgres:15-alpine
    container_name: ai_study_hub_db_local
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      # Port ngoài máy chủ (host) : Port trong container
      - '${DB_LOCAL_PORT}:5432'
    volumes:
      # Lưu trữ data xuống ổ đĩa cục bộ của Docker để không bị mất khi stop container
      - postgres_local_data:/var/lib/postgresql/data

volumes:
  postgres_local_data:
